const List<List<String>> facts=
[["1.Personality Starts in the Psyche",
"According to Freud, your self-perception stems from a belief in the ID, the ego, and the superego. These three factors make up the psyche, and ultimately the psyche makes up the self."],
["2.The Self Is A Representation of the Psyche",
"It was believed that people would repress emotions, thoughts, and traumas that didn’t serve their conscious minds. These repressed energies within the psyche are displayed through your behavior."],
["3.Our Psyche Is Made up of Three Parts",
"According to Freud’s theory of the psyche, we have three parts. The Id lies hidden in the unconscious mind. The ego is the version of ourselves that is conscious; this aspect regulates the other elements of the psyche. The superego is the critical voice within that questions our Id."],
["4.The Superego Drives Us",
"The superego takes on the voice of our environment’s social norms and influences. These factors will direct our Id and ego. So, humans are usually driven by the superego as it tends to tame our ego and question our Id."],
["5.Our Personality Changes As We Self-Actualize",
"Self-actualization comes from acknowledging your basic needs and what you may need to grow. The more we grow, the more we self-actualize, and so our personality will change accordingly."],
["6.Self-Actualization is an Ongoing Process",
"As we discover more of ourselves, we try to figure out the next growth steps, making us act differently to achieve the next steps of change. "],
["7.We Base Our Needs on a Hierarchy",
"According to Maslow’s Hierarchy of Needs, we aim to fulfill our full potential. This allows us to achieve the highest point within the hierarchy – self-transcendence."],
["8.Transcendence as the Ultimate Goal",
"Once the basic needs are satisfied, we can reach self-transcendence. This, in turn, allows us to help others and ensure that we make a change within the world around us."],
["9.Our Understanding of Personality is Skewed",
"If you asked ten people to define personality, you would probably receive ten different answers. Our understanding of personality is subjective, and each person, despite the best efforts of science, will view personality according to various descriptions."],
["10.Personality is More than Behaviors",
"Personality is defined by cognition, emotional patterns, and a characteristic set of behaviors. Much of our personality is influenced by various disorders from anxiety to ADHD and concerns elements like memory and your ability to learn."],
["11.Emotions are Powerful",
"According to studies done by Paul Ekman in the 1930s, your emotions can override your most innate drives and motivations. Things like disgust can override hunger, and happiness or sadness can compromise your attention, just to name a few."],
["12.We Are Our Truest Selves When Emotional",
"When we find ourselves in an emotional state, our actions, words, and choices indicate our true personalities. Ekman argues that personality is a reflection of emotion."],
["13.Happy People Tend to Be More Social",
"Martin Seligman, a pioneer in positive psychology, studied happiness and discovered three kinds of a happy life. Throughout his studies, it was found that social relationships will help bring about everlasting happiness."],
["14.Sociableness Does Not Guarantee Happiness",
"While being social cannot guarantee a happy life, it certainly adds an element of pleasure and service to others and inspires an aspect of personal growth."],
["15.Your Social Roles Will Influence Your Personality",
"In 1971, professor Phillip Zimbardo experimented with college students in the Stanford Prison Experiment. Zimbardo discovered that students placed in authoritative positions had changed their behavior (and personality) throughout this two-week trial cut short."],
["16.People Compromise Themselves to Fulfill Social Roles",
"The Stanford Prison Experiment shows that people will compromise on their dearest moral values to satisfy a social role. Some prison guards became more brutal and aggressive than they would be in normal circumstances."],
["17.Compulsive Behavior is Not a Personality Trait",
"Many individuals believe that OCD(compulsive behavior), in general, is a personality disorder and stems from dire and traumatic mental health issues. These behaviors are merely a coping mechanism."],
["18.Mental Health Issues Do Not Define Personality",
"Paul Salkovskis discusses obsessive thoughts and says that compulsive behavior is a series of rituals created to control unwanted intrusive thoughts. While these tendencies allow us to better cope with reality, it is not a defining factor."],
["19.Humans are Designed to Conform",
"Psychologist Solomon Asch conducted trials in the name of social psychology to distinguish how we interact with each other. The study determined how we neglect our intrinsic personality to conform to the general public. Studies show that one-third of participants had conformed solely because of their peers."],
["20.There Are Stages to Personality Development",
"Many debates encircled Erik Erikson’s psychosocial development theories. He devised an eight-stage process that broke down the stages of human development, each of which is a contributing factor to the overall personality."],
["21.External Influences Mostly Determine Personality",
"Erikson concluded that personality exists as an outcome of dealing with conflicts throughout our lives. Each stage presents an issue, and how we deal with it influences your current personality."],
["22.Our Experience Is Shaped by the Way We Handle Bad Things",
"There are two types of people in the world, those who feel crushed by bad experiences and those who accept it as a challenge. According to Boris Cyrulnik, how we cope with tragedy says that resilience is not an inherent trait but something we build and define for ourselves as we age."],
["23.Labeling Your Trauma May Make It Worse",
"To many people, your lived experience makes up the most significant chunk of our personality; it defines how we act in certain situations and react to stressors. The way we label our trauma describes how other people see it."],
["24.Other People’s Perception of Our Trauma Can Be Damaging",
"It is suggested that how other people interpret our labels of trauma can cause more damage to our self-esteem than the horrific experience itself."],
["25.The Roles We Accept in Our Families Can Determine Who We Are in the World",
"According to Virginia Satir, we tend to assume a position within our families to cover up emotional distress. These roles define who we are within the context of our families and can seep into our perception of ourselves once we take our place in the world."],
["26.We Are Made in the “Family Factory”",
"We learn to react to our family members, and these reactions can shape the role we assume when placed under stress. If we assume these roles enough, it can overwhelm our authentic selves.  If we are not conscious of this, we may take this role into our adult lives."],
["27.Healing the Family Can Heal the World",
"According to family therapy, once we acknowledge who we are within our families, whether we assume the role of distractor, leveler, computer, blamer, or placator, we continue to react to our families within these capacities. If this goes against our authentic selves, we may continue to experience deep unhappiness in our adult lives."],
["28.There Are Also Dysfunctional Family Roles",
"While much of psychology focuses on the norm, modern psychology attempts to analyze what is not normal. Dysfunctional family roles also exist."],
["29.If You’re Regularly Depressed, You May Need to Find Ecstasy",
"According to Mihaly Csikszentmihalyi, a state of ecstasy is achieved by achieving a sense of flow. Often, we find ourselves miserable, and we’re unsure why. According to this theory, we need to find a sense of focus, serenity, timelessness, and clarity by doing things that we enjoy and activities that engage us."],
["30.Our Preferences Define Our Experiences and Not Our Personality",
"Some people like to define themselves by their tastes; whether they’re cultured or not is usually displayed through what they choose to take into their lives daily. According to studies by Robert Zajonc, preference is irrational."],
["31.Preference Is Defined by Exposure",
"In the same breath, what we prefer is a product of what we’ve experienced throughout our lives. The more you see something, the more familiar you become with it, and you tend to like it. Think about that song on the radio that you love now."],
["32.Extroverts and Introverts Alike Have a Social Nature",
"The separation between introverts and extroverts has realigned our ideas of how important a social life is. We tend to think that this aspect of life is optional. According to William Glasser, improving your relationships helps improve mental health."],
["33.We Try to Choose Pleasure Over Pain",
"While this one is more aligned with happiness than personality, we think it’s somewhat relevant to understanding your personality. This dictates that we are innately programmed to choose what makes us happier: survival, belonging and love, freedom, power, and fun.   "],
["34.Lasting Psychological Problems Are Usually a Result of Problems in Personal Relationships",
"While there is merit to biochemical abnormalities that influence our personality, another overlooked aspect is that an imbalance in our relationships can destabilize our feelings of survival, love and belonging, fun, power, and freedom. If we course-correct these relationships, from parents to crushes, we may find a new balance with our psychological problems."],
["35.Doing a Crazy Thing Does Not Make You a Crazy Person",
"Social psychology argues that we need to understand people before judging them. The circumstances that prompted a sane person to do an insane thing are much more critical than the insane actions we may attribute to them."],
["36.Finding Meaning is Innate",
"Humans have the intrinsic ability to find meaning in life and the circumstances and events surrounding us. Erich Fromm considered it to be the defining characteristic of being human. He also thought it to be the difference between fulfillment and dissatisfaction."],
["37.Wholeness and Individuality are Mutually Exclusive",
"According to Fromm, we look for meaning to make things feel whole and create a sense of wholeness within ourselves. He also suggests that we also look for wholeness and purpose through our individuality on the flip side of the coin."],
["38.“Non -Productive” Is a Personality Type",
"Along the same line of thought, Fromm theorized four main character types. These non-productive types do not assume responsibility for their actions. These personality traits are receptive, exploitative, hoarding, and marketing. Fromm’s ideal is the productive personality that combines the best of each personality type."],
["39.Necrophilous Is the Most Destructive Personality",
"According to Fromm, there is also a fifth personality type. These people tend to see only destruction, evil, sickness, and death and seek to destroy. They tend to make sense of chaos by imposing law and order. Hitler is said to be a prime example of this personality type."],
["40.Inflexible Personality Types Miss Out on the Good Life",
"Carl Rogers posits that we tend to lead ourselves away from the “good life” if we are too rigid in our ways. If you allow yourself to choose what you’ll do at the moment, your life ill be more satisfying. Inflexible personality types tend to miss out on this happiness as they are too focused on predicting the future."],
["41.You Know Yourself Best",
"Psychology is pretty popular these days; with the range of mental health issues and generally trying to keep a healthy mind, psychologists are as influential as your regular GP. According to Carl Rogers, you know yourself best, and your psychologist should guide you to the answers in a type of therapy that takes a person-centered approach."],
["42.Insight May Be The Root Of All Evil",
"In psychotherapy, we are accustomed to asking what the root cause is before understanding the current issue. Paul Watzlawick believed that insight into the root causes of your problems might make the situation worse."],
["43.Understanding Root Causes Can Make You Blind To The Problem",
"In the same breath, understanding the root cause of your problems may make you blind to the actual problem and may make it harder to deal with the issue at hand (even after figuring out where it stems from). Personality types that dwell on the past causations are usually stuck in a loop as they struggle to find the solutions they need."],
["44.Illness is a Breakthrough",
"At the end of the 19th century, R.D Laing suggested that mental illness is not as bad as the stigmatism suggests. He means that mental illness should be valued and treated as a cathartic and transformative experience."],
["45.Neurotic Personality Types May be First To Admit They Need Help",
"Along the same line of thinking, R.D Laing says that personality disorders lead to important personal insights. People with neurotic tendencies will assume that anything out of “the norm” may need to be looked at with a fine-tooth comb. Thus, they’ll usually be the first to assume their illness as a sign to get help."],
["46.Reflective Traits Will Help You Learn Faster",
"People who possess reflective personality traits will often pause after failures to assess and analyze what went wrong and what tools surround them to improve the situation."],
["47.Conscientious People May Be More Successful",
"Conscientious people are generally more reflective. They’ll use this to attack the problem differently and achieve success afterward. This allows them to train their instincts and retain knowledge."],
["48.We Remember Unfinished Things More",
"In the same breath, Bluma Zeigarnik suggests that unfinished tasks are usually remembered better than finished ones. If a task lacks closure, we tend to obsess over it a little bit more and will remember it in greater detail than tasks that have satisfied our desire for completion."],
["49.Rigid Neurological Traits Stifles Our Ability To Accept New Beliefs",
"If you’re the kind of person who holds their beliefs near and dear without room for change, you may find it harder to accept contradictory beliefs or even grant them the time of day to understand them."],
["50.Cognitive Dissonance is Important For Growth",
"This kind of cognitive dissonance is vital for growth and personal development. More flexible personalities will easily accept contradictions and analyze and learn from them to promote personal development."],
["51.Happy People Remember More",
"According to studies done by Gordon H. Bower, a happy mood allows us to remember the good things better, whereas a bad mood makes us more susceptible to remembering the bad stuff. Happier people will be happier as they remember more positive events and memories, whereas the opposite is true for unhappy people."],
["52.Obedience Is Innate",
"According to Stanley Milgram’s experiments on obedience, it has been devised that agreeable or likable people will act according to an authority figure even if it goes against their morals and values. We are compelled to comply with Conformity, especially if we’re agreeable by nature."],
["53.“Intelligence Is What You Use When You Don’t Know What to Do” – Jean Piaget",
"Our personalities are usually shaped by the environments and teachers while growing up in terms of learning. Many teachers hope to mold students in a manner that resembles a typical adult. Jean Piaget suggested that students should be led into new modes of thinking instead of a form of molding."],
["54.Conforming Personality Types Struggle With Individuality",
"In essence, Piaget posited that students should be guided toward themselves through introspection and moral growth. People with conforming tendencies may struggle with this later in life as they’re accustomed to following what happens around them instead of instinctively forging their path."],
["55.Human Development Occurs By Watching Others",
"Conversely, we cannot deny that the basic skills needed for survival, namely cultural, interpersonal, and individual needs, are taught by what we see in our surroundings. What we are exposed to shapes our personality."],
["56.We Need Good Role Models as Kids",
"Therefore, children absorb accumulated wisdom and will need to develop their intelligence and personality through role models around them. This is why having good role models around us as kids are crucial."],
["57.Attachment Behavior Is an Integral Part of Human Nature",
"According to attachment theory analyzed by John Bowlby, we are biologically programmed to be attached to our mothers. A break in this critical period of life (first 24 months) may suffer severe and permanent damage to our development."],
["58.Attachment Styles Are Part of Our Personality",
"In recent years, attachment styles have been explored to understand ourselves and our relationships. The kind of person you become in a relationship is in direct proportion to the relationships we build with our parents during the critical periods of our lives"],
["59.Girls Are Smarter Than Boys",
"This controversial statement has been debated for years. In essence, though, it is false. The significant difference between both genders is that females tend to put more effort into their work and will acquire more hobbies and interests. This, in turn, means that girls may get better grades in school."],
["60.Assertive Personalities Have a Higher Learning Retention",
"More assertive and active personalities tend to learn and retain more than passive learners and submissive personalities. Eleanor E. Maccoby challenged intelligence stereotypes to determine which factors made students brighter than others."],
["61.Gender is Sometimes Considered a Personality Trait",
"What is the difference between boys and girls? Why do they act differently at all? Gender Development theory suggests that boys and girls are treated differently by their parents. This guides them to become more masculine or feminine."],
["62.Women Are More Empathetic and Emotional",
"Albert Bandura conducted studies on gender development and has reiterated that women tend to be more dependent, and display empathy and emotional expressiveness more often than their male counterparts, as this was suggested as acceptable behavior while growing up."],
["63.Men Are Self-Reliant and Independent",
"Conversely, men are usually applauded for behavior that displays independence, self-reliance, and emotional control. This cements their behavior throughout their lives and will foster men who struggle to show weakness and ask for help."],
["64.Morality Develops in Six Stages",
"Throughout our lives, we develop a sense of morality. Many people view their morality as a force that guides their personality. This allows us to question the intention of our behavior. This theory of morality suggests that we determine our moral code through interaction, respect, love, and empathy."],
["65.Some People Are Convergent Thinkers",
"According to J.P Guilford, there are two types of intelligence. One is called convergent thinking. Convergent thinking allows us to develop one answer and can be tested through standardized testing. "],
["66.Other People are Divergent Thinkers",
"The opposite of convergent thinking allows us to think of many different answers and usually indicates a capacity for problem-solving and imagination. This is known as divergent thinking."],
["67.Gordon Allport is the Founding Father of Personality Psychology",
"While many aspects of psychology focused on psychoanalysis, behaviorism, or cognitive psychology, Gordon Allport was the first to develop personality psychology on its own, exclusive of other psychological forms."],
["68.Personality Was Considered the Self",
"Before the 19th century,  personality was defined by knowing the self, intelligence, and ego. Thus many facets of psychology are interwoven and interlinked with personality. "],
["69.Personality Focuses on the Present",
"Personality Psychology focuses on the present, while every other facet of psychology looks at the past and avoids acknowledging current motivations and contexts. To understand personality, you’ll have to look at the modern context within recent actions and motivations."],
["70.People Have Cardinal Traits",
"These are considered your “ruling passions.” The things that steer you forward usually dominate your personality. Many people typically become known solely for these traits, such as altruism, kindness, or ruthlessness. "],
["71.Cardinal Traits Are Rare",
"Not everyone has a cardinal trait. It is considered quite rare and most commonly attributed to people who have since become famous for possessing that specific trait."],
["72.People Have Common Traits",
"While not everyone has a cardinal trait, everyone has common traits. These are the basic adjectives we use to describe ourselves, like honesty or aggression. If you do not possess any cardinal traits, your personality is shaped by your common traits."],
["73.People Have Secondary Traits",
"These are the quirks that some people become known for. Your secondary traits are defined by the things that happen in specific circumstances. For example, laughing in appropriate situations is a prevalent secondary trait."],
["74.Others Forge Our Personality",
"According to Gordon Allport, your personality is forged by others and other people that surround you in your critical growth period."],
["75.Personality Was Not Researched Empirically",
"While most research in the academic world is done through empirical methods and uses scientific methods to formulate official hypotheses and draw tested conclusions, personality was initially nomothetic and highly theoretical."],
["76.Internal Forces Govern Us",
"According to Gordon Allport, we are all governed by internal forces, which he calls Genotypes. These Genotypes define how we retain information and use it to interact with the external world."],
["77.Phenotypes Are External Forces",
"Alongside Genotypes, we also have Phenotypes. These determine how we accept our surroundings and allow others to influence our behaviors."],
["78.Insanity is Genius with a Low IQ",
"According to Hans J. Eysenck, we are all predisposed to overinclusive thinking. In people with a high IQ, this translates to genius. Although, in someone with a low IQ, this kind of thinking combines with psychotic symptoms and leads to insanity."],
["79.There are Four Types of Temperament",
"According to Galen, temperament is important in understanding personality and was the basis for other personality models. People are usually phlegmatic, sanguine, melancholic, or choleric."],
["80.Theorists Believed That Your Temperament Determined Your Illnesses",
"According to those four kinds of temperament, psychologists used to believe that this indicates the kind of person you are and the kind of physical illnesses you’ll have."],
["81.We Fall Into Various Superfactors",
"Furthermore, Eysenck devised a model of personality that includes introversion and extraversion and neuroticism, and emotional stability. These super factors work hand in hand with Galen’s Four Temperaments."],
["82.Eysenck Was the First to Define Personality Beyond the Norm",
"While most personality and psychology studies focused on the norm, Eysenck was the first to study personality from a mental institution."],
["83.Three Key Motivations Drive Performance",
"According to David McClelland, motivation is driven by three varying components. Motivation is unconscious, so adding achievement, power, and affiliation will help increase your motivations."],
["84.Behavior Can Be Predicted",
"Walter Mischel suggests an interaction between the person, their personality, a situation, and how they will react. These external factors and context help predict behavior."],
["85.The Three Faces of Eve Inspired MPD",
"The Split movie franchise popularized Multiple Personality Disorder. The disorder itself was first brought to light by a person named Eve. She displayed light and dark versions of herself and a completely different personality, Jane."],
["86.We Conform to Multiple Personality Traits",
"In the 1940s, multiple personality traits were popularized. This is what we commonly use now to assess personality. It describes personality as a complex concept that cannot be regarded with a narrow description."],
["87.Your Personality Falls Along a Spectrum",
"There are five factors in multiple personality trait theories. Our personality falls within this spectrum. The multiple theories are extroversion, agreeableness, conscientiousness, neuroticism, and openness to experience."],
["88.The Big-Five Inspired the 16 Factors",
"Goldberg’s Big Five personality model was the groundwork used by Cattell for his 16 factors that are still used in common personality testing."],
["89.Personality is Defined Along a 16PF Spectrum",
"According to Cattell, 16 personality factors can be taken into consideration."],
["90.The MBTI indicator Is a Clear Personality Indication",
"The MBTI personality type indicator is based on Jung’s psychosocial theory and defines personality into 16 different categories. We understand them as INTJ or ESFP, etc."],
["91.There are Many Other Personality Type Indicators",
"While the MBTI personality type indicator is the most used, there are multiple other ways to test your personality. Things like enneagrams and color tests indicate what you’re like based on your intelligence and other factors."],
["92.Leaders Are Usually Open to Experiences",
"According to the Big Five personality model, openness to experiences dictates whether someone will be willing to try something new and step out of their comfort zones. Leaders tend to possess this trait."],
["93.Conscientious People Are Usually Very Prepared",
"People with high conscientiousness are usually quite prepared as they tend to value order, a sense of duty, and self-discipline."],
["94.People Are Extraverted or Introverted",
"Most people would fall along with the introversion and extraversion spectrum. High extraversion correlates to good social relationships and very outgoing roles within the workplace and community. Introverts tend to be more reserved and hide from the significant spotlight."],
["95.Loyal People Are Usually Quite Agreeable",
"Agreeableness correlates to how liked someone is and provides insight into how trustworthy people may think they are. People with low agreeableness would usually be disliked by their peers."],
["96.Neurotic People Are Usually Quite Emotional",
"Neuroticism usually defines how comfortable someone is in their bodies and how confident they are in the world. People with low neuroticism are generally confident, and highly neurotic people are pretty anxious."],
["97.Birth Order Influences Personality",
"The order in which you and your siblings are born can influence your behavior and thus your personality. It is said that the order is not the same in every family, and thus, the theory is somewhat unstable."],
["98.Personality Is Stable",
"For most people, your personality, once consolidated, remains unchanged throughout your life."],
["99.Personality Can Influence Personal Preference",
"Your personality can determine what you prefer. Whether you’re conscientious or neurotic, it can determine which presidential candidate you choose and your taste in music."],];